openapi: 3.0.0
info:
  title: JSONPlaceholder API
  version: 1.0.0
  description: |-
    A free fake API for testing and prototyping. This API allows users to create and retrieve user post.
servers:
  - url: https://jsonplaceholder.typicode.com
paths:
  /posts:
    get:
      operationId: getPosts
      summary: Get all posts
      description: Retrieve a list of all posts.
      responses:
        '200':
          description: A list of posts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      operationId: createPost
      summary: Create a new post
      description: Create a new post in the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostInput'
      responses:
        '201':
          description: The created post.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
  /posts/{id}:
    get:
      operationId: getPostById
      summary: Get a post by ID
      description: Retrieve a single post by its ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single post.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
components:
  schemas:
    Post:
      type: object
      properties:
        userId:
          type: integer
        id:
          type: integer
        title:
          type: string
        body:
          type: string
    PostInput:
      type: object
      properties:
        title:
          type: string
        body:
          type: string
        userId:
          type: integer
      required:
        - title
        - body
        - userId